#TODO : All xpath details here noted:
content_urls_xpath='//section//following-sibling::article[@class="post"]//p//a[contains(text(),"Click for more information...")]//@href'
title_xpath='//article[@class="post infopage"]//header//h1/a/@title'
url_xpath='//article[@class="post infopage"]//header//h1/a/@href'
content_type_xpath='//article[@class="post infopage"]//aside//div//h1//text()'
genre_xpath='//article[@class="post infopage"]//aside//div[@class="genre"]//h5//text()'
img_xpath='//article[@class="post infopage"]//aside//div//img//@src'
history_tags_xpath='//article[@class="post infopage"]/p/em//strong//text()'
key_xpath='//article[@class="post infopage"]//p//em//strong[contains(text(),"%s")]//following-sibling::text()'
other_details_xpath='//article[@class="post infopage"]//p//strong//text()'
date_xpath='//p[strong[contains(text(),"%s")]]//following::text()'
description_xpath='//p[strong[contains(text(),"%s")]]//following-sibling::p//text()'
rating_xpath='//p[strong[contains(text(),"%s")]]//span//text()'
year_xpath='//p[strong[contains(text(),"%s")]]//following-sibling::text()'
duration_xpath='//p[strong[contains(text(),"%s")]]//following-sibling::text()'
record_lang_xpath='//p[strong[contains(text(),"%s")]]//following-sibling::text()'
subtitles_xpath='//p[strong[contains(text(),"%s")]]//following-sibling::text()'
director_xpath='//p[strong[contains(text(),"%s")]]//a//text()'
cast_xpath='//p[strong[contains(text(),"%s")]]/a/text()'
available_season_xpath='//p[strong[contains(text(),"%s")]]//following-sibling::text()'
